In [6]:
import pandas as pd
import numpy as np

## Explore the data

In [17]:
hurdat = pd.read_csv('Processed_hurricane_florida_data.csv', index_col = 'date')

hurdat.drop(hurdat.columns[0], axis = 1, inplace = True)
hurdat.loc[hurdat['min_pressure'] == -999, 'min_pressure'] = np.nan
hurdat.loc[hurdat['max_wind'] == -999, 'max_wind'] = np.nan
hurdat.index = pd.to_datetime(hurdat.index)
hurdat['year'] = hurdat.index.year

hurdat

,storm_id,storm_name,time,status,latitude,longitude,max_wind,min_pressure,category,year
date,,,,,,,,,,
1851-06-25,AL011851,UNNAMED,0,HU,28.0N,94.8W,80.0,NaN,1,1851
1851-06-25,AL011851,UNNAMED,600,HU,28.0N,95.4W,80.0,NaN,1,1851
1851-06-25,AL011851,UNNAMED,1200,HU,28.0N,96.0W,80.0,NaN,1,1851
1851-06-25,AL011851,UNNAMED,1800,HU,28.1N,96.5W,80.0,NaN,1,1851
1851-06-25,AL011851,UNNAMED,2100,HU,28.2N,96.8W,80.0,NaN,1,1851
...,...,...,...,...,...,...,...,...,...,...
2023-10-23,AL212023,TWENTY-ONE,1800,TD,11.5N,83.2W,25.0,1007.0,0,2023
2023-10-24,AL212023,TWENTY-ONE,0,TD,12.2N,83.4W,25.0,1007.0,0,2023
2023-10-24,AL212023,TWENTY-ONE,130,TD,12.4N,83.5W,25.0,1007.0,0,2023
2023-10-24,AL212023,TWENTY-ONE,600,TD,13.0N,83.8W,25.0,1007.0,0,2023
2023-10-24,AL212023,TWENTY-ONE,1200,LO,13.5N,84.4W,20.0,1007.0,0,2023

In [27]:
temp = pd.read_csv('Processed_florida_temp_data.csv', index_col = 'Date')
temp.index = pd.to_datetime(temp.index)
temp['year'] = temp.index.year
temp['year'] = temp.index.year
temp['Temperature'] = pd.to_numeric(temp['Temperature'], errors='coerce')  # Convert invalid to NaN
temp.loc[temp['Temperature'] == -9999] = np.nan
temp.dropna(subset=['Temperature'], inplace=True)  # Drop rows with NaN if necessary

temp

             Station ID Element  Temperature    year
Date
1939-01-01  USC00293225    TAVG        141.0  1939.0
1940-01-01  USC00293225    TAVG        210.0  1940.0
1941-01-01  USC00293225    TAVG        510.0  1941.0
1942-01-01  USC00293225    TAVG        535.0  1942.0
1947-01-01  USC00293225    TAVG        218.0  1947.0
...                 ...     ...          ...     ...
1974-12-01  USC00293225    TAVG        297.0  1974.0
1975-12-01  USC00293225    TAVG        493.0  1975.0
1976-12-01  USC00293225    TAVG        292.0  1976.0
1977-12-01  USC00293225    TAVG        794.0  1977.0
1978-12-01  USC00293225    TAVG        248.0  1978.0

[459 rows x 4 columns]

In [37]:
prcp = pd.read_csv('Processed_florida_prcp_data.csv', index_col = 'Date')
prcp['Precipitation (mm)'] = pd.to_numeric(prcp['Precipitation (mm)'], errors='coerce')  # Convert invalid to NaN
# prcp.dropna(inplace=True)
prcp.index = pd.DatetimeIndex(prcp.index)
prcp['year'] = prcp.index.year
prcp['month'] = prcp.index.month
prcp

,Station ID,Station Name,Latitude,Longitude,Elevation,Precipitation (mm),Measurement flag,Quality control flag,Source flag,Source index,year,month
Date,,,,,,,,,,,,
1880-01-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,343,,,D,9612,1880,1
1880-02-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,2138,,,D,9612,1880,2
1880-03-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,330,,,D,9612,1880,3
1880-04-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,1295,,,D,9612,1880,4
1880-05-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,107,,,D,9612,1880,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1924-08-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,467,,,D,9612,1924,8
1924-09-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,404,,,D,9612,1924,9
1924-10-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,249,,,D,9612,1924,10
1924-11-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,1502,,,D,9612,1924,11
1924-12-01,ASN00048154,"""FLORIDA STATION""",-31.5,146.4,NaN,355,,,D,9612,1924,12

In [31]:
merged_data = pd.merge(hurdat, temp[['Temperature', 'year']], 
                       on=['year'], how='left')
merged_data.dropna()
merged_data.index = merged_data['year']
merged_data

,storm_id,storm_name,time,status,latitude,longitude,max_wind,min_pressure,category,year,Temperature
year,,,,,,,,,,,
1851,AL011851,UNNAMED,0,HU,28.0N,94.8W,80.0,NaN,1,1851,NaN
1851,AL011851,UNNAMED,600,HU,28.0N,95.4W,80.0,NaN,1,1851,NaN
1851,AL011851,UNNAMED,1200,HU,28.0N,96.0W,80.0,NaN,1,1851,NaN
1851,AL011851,UNNAMED,1800,HU,28.1N,96.5W,80.0,NaN,1,1851,NaN
1851,AL011851,UNNAMED,2100,HU,28.2N,96.8W,80.0,NaN,1,1851,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2023,AL212023,TWENTY-ONE,1800,TD,11.5N,83.2W,25.0,1007.0,0,2023,NaN
2023,AL212023,TWENTY-ONE,0,TD,12.2N,83.4W,25.0,1007.0,0,2023,NaN
2023,AL212023,TWENTY-ONE,130,TD,12.4N,83.5W,25.0,1007.0,0,2023,NaN
2023,AL212023,TWENTY-ONE,600,TD,13.0N,83.8W,25.0,1007.0,0,2023,NaN
2023,AL212023,TWENTY-ONE,1200,LO,13.5N,84.4W,20.0,1007.0,0,2023,NaN